Repository acts-project/algebra-plugins, pull requests merged in 2025-03, with the labels that each got.

#151 feat: add pre-commit checks to repo
  .github/workflows/checks.yml
  .pre-commit-config.yaml
  benchmarks/CMakeLists.txt
  tests/CMakeLists.txt
Labels: enhancement

#152 fix: build Vc plugin for apple clang
  benchmarks/CMakeLists.txt
  frontend/CMakeLists.txt
  math/CMakeLists.txt
  storage/CMakeLists.txt
  storage/common/include/algebra/storage/matrix.hpp
  storage/common/include/algebra/storage/vector.hpp
  tests/CMakeLists.txt
Labels: bug

#148 feat: Cleanup benchmark names and add inversion and determinant
  benchmarks/array/array_matrix.cpp
  benchmarks/common/include/benchmark/common/benchmark_base.hpp
  benchmarks/common/include/benchmark/common/benchmark_matrix.hpp
  benchmarks/common/include/benchmark/common/benchmark_transform3.hpp
  benchmarks/common/include/benchmark/common/benchmark_vector.hpp
  benchmarks/common/include/benchmark/common/register_benchmark.hpp
  benchmarks/eigen/eigen_matrix.cpp
  benchmarks/vc_aos/vc_aos_matrix.cpp
  math/eigen/include/algebra/math/impl/eigen_matrix.hpp
Labels: enhancement

#150 fix: algorithm selection for 4x4 matrices
  frontend/array_cmath/include/algebra/array_cmath.hpp
  frontend/vc_aos/include/algebra/vc_aos.hpp
Labels: bug, performance

#149 feat: loop unrolling and switch to constexpr
  common/include/algebra/qualifiers.hpp
  math/cmath/include/algebra/math/impl/cmath_matrix.hpp
  math/cmath/include/algebra/math/impl/cmath_operators.hpp
  math/cmath/include/algebra/math/impl/cmath_vector.hpp
  math/eigen/include/algebra/math/impl/eigen_matrix.hpp
  math/eigen/include/algebra/math/impl/eigen_transform3.hpp
  math/eigen/include/algebra/math/impl/eigen_vector.hpp
  math/fastor/include/algebra/math/impl/fastor_matrix.hpp
  math/fastor/include/algebra/math/impl/fastor_transform3.hpp
  math/fastor/include/algebra/math/impl/fastor_vector.hpp
  math/generic/include/algebra/math/algorithms/matrix/decomposition/partial_pivot_lud.hpp
  math/generic/include/algebra/math/algorithms/matrix/determinant/cofactor.hpp
  math/generic/include/algebra/math/algorithms/matrix/determinant/hard_coded.hpp
  math/generic/include/algebra/math/algorithms/matrix/determinant/partial_pivot_lud.hpp
  math/generic/include/algebra/math/algorithms/matrix/inverse/cofactor.hpp
  math/generic/include/algebra/math/algorithms/matrix/inverse/hard_coded.hpp
  math/generic/include/algebra/math/algorithms/matrix/inverse/partial_pivot_lud.hpp
  math/generic/include/algebra/math/impl/generic_matrix.hpp
  math/generic/include/algebra/math/impl/generic_transform3.hpp
  math/generic/include/algebra/math/impl/generic_vector.hpp
  math/smatrix/include/algebra/math/impl/smatrix_matrix.hpp
  math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
  math/smatrix/include/algebra/math/impl/smatrix_vector.hpp
  math/vc_aos/include/algebra/math/impl/vc_aos_transform3.hpp
  math/vc_aos/include/algebra/math/impl/vc_aos_vector.hpp
  math/vc_soa/include/algebra/math/impl/vc_soa_boolean.hpp
  math/vc_soa/include/algebra/math/impl/vc_soa_math.hpp
  math/vc_soa/include/algebra/math/impl/vc_soa_matrix.hpp
  math/vc_soa/include/algebra/math/impl/vc_soa_vector.hpp
  storage/cmath/include/algebra/storage/impl/cmath_getter.hpp
  storage/common/include/algebra/storage/matrix.hpp
  storage/common/include/algebra/storage/matrix_getter.hpp
  storage/common/include/algebra/storage/vector.hpp
  storage/eigen/include/algebra/storage/impl/eigen_getter.hpp
  storage/fastor/include/algebra/storage/impl/fastor_getter.hpp
  storage/fastor/include/algebra/storage/impl/fastor_matrix.hpp
  storage/smatrix/include/algebra/storage/impl/smatrix_getter.hpp
Labels: enhancement, performance

#156 ref: Improve the stream operator for matrices and vectors
  utils/include/algebra/utils/print.hpp
Labels: cleanup

#157 ref: Update externals
  extern/benchmark/CMakeLists.txt
  extern/fastor/CMakeLists.txt
  extern/googletest/CMakeLists.txt
  extern/vc/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
Labels: enhancement

#158 Prevent CMake flags from propagating to parent
  cmake/algebra-plugins-compiler-options-cpp.cmake
  cmake/algebra-plugins-compiler-options-cuda.cmake
  cmake/algebra-plugins-compiler-options-sycl.cmake
Labels: bug

#160 feat: approximately equal for algebra types
  common/include/algebra/type_traits.hpp
  math/fastor/include/algebra/math/impl/fastor_transform3.hpp
  storage/array/include/algebra/storage/array.hpp
  storage/common/include/algebra/storage/matrix.hpp
  storage/common/include/algebra/storage/vector.hpp
  storage/eigen/include/algebra/storage/eigen.hpp
  storage/fastor/include/algebra/storage/fastor.hpp
  storage/smatrix/include/algebra/storage/smatrix.hpp
  storage/vc_aos/CMakeLists.txt
  storage/vc_aos/include/algebra/storage/impl/vc_aos_approximately_equal.hpp
  storage/vc_aos/include/algebra/storage/vc_aos.hpp
  storage/vc_soa/include/algebra/storage/vc_soa.hpp
  storage/vecmem/include/algebra/storage/vecmem.hpp
  tests/common/test_host_basics.hpp
  tests/vc_soa/vc_soa.cpp
  utils/CMakeLists.txt
  utils/include/algebra/utils/approximately_equal.hpp
Labels: bug, enhancement

#159 feat: Algebra type casts
  frontend/vc_soa/include/algebra/vc_soa.hpp
  math/eigen/CMakeLists.txt
  math/eigen/include/algebra/math/impl/eigen_transform3.hpp
  math/fastor/CMakeLists.txt
  math/fastor/include/algebra/math/impl/fastor_transform3.hpp
  math/generic/CMakeLists.txt
  math/generic/include/algebra/math/impl/generic_transform3.hpp
  math/smatrix/CMakeLists.txt
  math/smatrix/include/algebra/math/impl/smatrix_transform3.hpp
  math/vc_aos/CMakeLists.txt
  math/vc_aos/include/algebra/math/impl/vc_aos_transform3.hpp
  storage/vc_aos/CMakeLists.txt
  storage/vc_soa/CMakeLists.txt
  storage/vc_soa/include/algebra/storage/impl/vc_soa_casts.hpp
  storage/vc_soa/include/algebra/storage/vc_soa.hpp
  tests/common/test_host_basics.hpp
  tests/vc_soa/vc_soa.cpp
  utils/CMakeLists.txt
  utils/include/algebra/utils/casts.hpp
Labels: enhancement
